// ==============================================================================
// 🔥 Code automatically generated by ENERGY GUI Designer. DO NOT EDIT
// 🔥 ENERGY GUI 设计器自动生成代码. 不能编辑
// ==============================================================================
// 🔍 基本信息
//     生成工具: ENERGY GUI Designer v1.0.0
//     生成时间: 2026-04-05 14:23:22
//     设计文件: form1.ui
//     用户文件: form1.go
//     功能描述: 基于 ENERGY GUI 框架的实现, 包含UI组件创建
// ==============================================================================

package app

import (
	"github.com/energye/energy/v3/window"
	"github.com/energye/energy/v3/wv"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
	lclTypes "github.com/energye/lcl/types"
)

type TForm1 struct {
	window.TWindow
	Webview1 wv.IWebview
}

var Form1 TForm1

// FormCreate 窗体创建接口实现. 自动调用
func (m *TForm1) FormCreate(sender lcl.IObject) {
	m.TWindow.InternalBeforeFormCreate()
	// 设置窗体属性
	m.SetCaption("Form1")
	m.SetHeight(600)
	m.SetLeft(200)
	m.SetName("Form1")
	m.SetTop(0)
	m.SetWidth(800)
	// 初始化组件
	m.initComponents()
	// 调用用户创建窗体事件
	m.OnFormCreate(sender)
	m.TWindow.FormCreate(sender)
}

// OnShow 窗口显示事件
func (m *TForm1) OnShow(sender lcl.IObject) {
	m.TWindow.OnShow(sender)
	m.OnFormShow(sender)
}

// OnCloseQuery 窗体关闭前询问事件
func (m *TForm1) OnCloseQuery(sender lcl.IObject, canClose *bool) {
	if !m.OnFormCloseQuery(sender, canClose) {
		m.TWindow.OnCloseQuery(sender, canClose)
	}
}

// OnClose 仅当 OnCloseQuery 中 CanClose 被设置为 True 后会触发
func (m *TForm1) OnClose(sender lcl.IObject, closeAction *types.TCloseAction) {
	if !m.OnFormClose(sender, closeAction) {
		m.TWindow.OnClose(sender, closeAction)
	}
}

// initComponents 初始化组件
func (m *TForm1) initComponents() {
	// 组件初始化和设置属性
	m.Webview1 = wv.NewWebview(m)
	m.Webview1.SetAlign(lclTypes.AlClient)
	m.Webview1.SetCaption("Webview1")
	m.Webview1.SetHeight(50)
	m.Webview1.SetLeft(0)
	m.Webview1.SetName("Webview1")
	m.Webview1.SetTop(0)
	m.Webview1.SetWidth(170)
	m.Webview1.SetParent(m)

}
